# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Vitalii Mikhailov
username: Aragas
email: personal@aragas.org
description: > # this means to ignore newlines until "baseurl:"
  Principal .NET Developer / Software Engineer / System Administrator / DevOps Engineer
#baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "https://aragas.org" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: Aragasas
github_username:  Aragas
#facebook_username: StartBootstrap
#instagram_username: beyonce
stackoverflow_url: https://stackoverflow.com/users/17339181/aragas
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
#address_street: None
address_city: Chisinau
address_state: Moldova
#address_zip: 00000

# Build settings
markdown: kramdown

includes:
- .well-known
